### ISSUE TITLE
Tweak updateDrink to use Mongoose update

### ISSUE THREAD

**Issue by frindaddy** [frindaddy/mixd#36]
updateDrink() currently deletes the drink entry, then creates a new one. Not very clean or safe if the post fails after the delete. Change this to use the Mongoose update command like updating ingredients.

**Comment by sidezbros** [comment]
Didn't change to use the internal mongoose update function, but I fixed the bug that inspired this issue. There was a database ID collision error that has been corrected. This issue can be revisited if there are any other bugs with the current implementation.
